"""Benchmark tables from out/*/result.json (written to docs/benchmark_results.md by run_all.sh).

Reference: there is no tape/laser ground truth for the sample captures, so the
LiDAR tier on each capture is the reference for the video and photo tiers on
the same footage. Tape ground truth plugs in via docs/ground_truth_template.csv
(scripts/score_gt.py) when available.
"""
import json
from pathlib import Path

OUT = Path("out")
CAPTURES = ["single_room", "floor_only", "with_ceiling"]


def load(name):
    p = OUT / name / "result.json"
    return json.loads(p.read_text()) if p.exists() else None


def hw(m):
    return (m["hi"] - m["lo"]) / 2


def summary(d):
    rooms = d["rooms"]
    walls = [w for r in rooms for w in r["walls"]]
    ops = [o for r in rooms for o in r["openings"]]
    return {
        "rooms": len(rooms),
        "footprint": d["stitched_plan"]["footprint_area"],
        "adj": len(d["stitched_plan"]["adjacency"]),
        "walls": len(walls),
        "wall_hw_med": sorted(hw(w["length"]) for w in walls)[len(walls) // 2] if walls else None,
        "doors": sum(o["type"] == "door" for o in ops),
        "windows": sum(o["type"] == "window" for o in ops),
        "ceil": [r["ceiling_height"]["value"] for r in rooms],
        "ceil_note": next((r["ceiling_height"]["note"].split(";")[0] for r in rooms if "note" in r["ceiling_height"]), None),
        "damage": len(d["damage"]),
        "flags": len(d["concealed_damage_flags"]),
        "scope": len(d["scope"]),
        "runtime": d["capture"].get("runtime_s"),
        "drift": d["stitched_plan"]["drift_correction"],
    }


def fmt(m):
    return f"{m['value']:.2f} [{m['lo']:.2f}, {m['hi']:.2f}]"


def main():
    print("# Benchmark results (regenerated by scripts/run_all.sh)\n")
    print("Reference = LiDAR tier on the same capture (no tape ground truth for the sample data).\n")
    print("## Per tier\n")
    print("| capture | tier | rooms | adjacencies | doors | windows | footprint m² [90% CI] | median wall ±m | ceilings m | damage / flags / scope | runtime s |")
    print("|---|---|---|---|---|---|---|---|---|---|---|")
    for c in CAPTURES:
        for tier in ("lidar", "video", "photo"):
            d = load(f"{tier}_{c}")
            if not d:
                print(f"| {c} | {tier} | not run | | | | | | | | |")
                continue
            s = summary(d)
            ceil = ", ".join(f"{x:.2f}" for x in s["ceil"]) + (f" ({s['ceil_note']})" if s["ceil_note"] else "")
            print(f"| {c} | {tier} | {s['rooms']} | {s['adj']} | {s['doors']} | {s['windows']} | {fmt(s['footprint'])} | "
                  f"{s['wall_hw_med']:.3f} | {ceil} | {s['damage']} / {s['flags']} / {s['scope']} | {s['runtime']} |")

    print("\n## Cross-tier footprint vs LiDAR reference\n")
    print("| capture | tier | footprint | LiDAR | error % | LiDAR value inside tier's interval? |")
    print("|---|---|---|---|---|---|")
    for c in CAPTURES:
        ref = load(f"lidar_{c}")
        if not ref:
            continue
        rf = ref["stitched_plan"]["footprint_area"]["value"]
        for tier in ("video", "photo"):
            d = load(f"{tier}_{c}")
            if not d:
                continue
            f = d["stitched_plan"]["footprint_area"]
            print(f"| {c} | {tier} | {fmt(f)} | {rf:.2f} | {100 * (f['value'] - rf) / rf:+.1f} | "
                  f"{'yes' if f['lo'] <= rf <= f['hi'] else 'NO'} |")

    print("\n## Drift ablation (LiDAR tier, stitched footprint)\n")
    print("| capture | correction on | correction off | heading corrected (max deg) | loop closure |")
    print("|---|---|---|---|---|")
    for c in CAPTURES:
        on, off = load(f"lidar_{c}"), load(f"lidar_{c}_nodrift")
        if not on or not off:
            continue
        det = on["stitched_plan"]["drift_detail"]
        loop = det["loop"]
        lc = f"closed, offset {loop['offset_m']} m over {loop['path_m']} m" if loop.get("closed") else loop.get("reason", "no")
        print(f"| {c} | {fmt(on['stitched_plan']['footprint_area'])} ({summary(on)['rooms']} rooms) | "
              f"{fmt(off['stitched_plan']['footprint_area'])} ({summary(off)['rooms']} rooms) | "
              f"{det['heading_correction_deg_max']} | {lc} |")

    print("\n## Fix loop: damage detector before / after (LiDAR tier)\n")
    print("| capture | before: regions (classes on floor) | after: regions | after: flags / scope |")
    print("|---|---|---|---|")
    for c in CAPTURES:
        b, a = load(f"fixloop_before_{c}"), load(f"fixloop_after_{c}")
        if not b or not a:
            continue
        bad = sum(1 for x in b["damage"] if x["surface_id"].endswith("_floor") and x["class"] != "water_stain")
        print(f"| {c} | {len(b['damage'])} ({bad} impossible) | {len(a['damage'])} | "
              f"{len(a['concealed_damage_flags'])} / {len(a['scope'])} |")


if __name__ == "__main__":
    main()
